### ISSUE TITLE
TW, DK - Implement "Hit Test"

### ISSUE THREAD

**Issue by horstgruber** [eggeral/3d-playground#26]

**Comment by horstgruber** [comment]
##  TODO
- [x] get mouse coordinates from beam 
- [ ] get all marked objects, which are on this beam
- [ ] highlight all affected objects

##  Acceptance Criteria
* on mouse click all obects on beam are highlighted
